version: "3.8"

services:
  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SOKETI_METRICS_ENABLED: ${SOKETI_METRICS_ENABLED:-1}
      SOKETI_DEBUG: ${SOKETI_DEBUG:-1}
      SOKETI_PORT: ${SOKETI_PORT:-6001}
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "9601:9601"
